authors:
- mani.m@continube.com
domain: continube
createdDate: 12/08/2024
name: FetchAWSUserDetails
displayName: FetchAWSUserDetails
version: '1.0'
description: FetchAWSUserDetails
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: PermissionConfigFile
  description: PermissionConfigFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: AWSUserDetails
  description: AWS User Details
  type: FILE
- name: LogFile
  description: Log File
  type: FILE