userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY" 
        SecretKey: "$AWS_SECRET_KEY"
      AWSRole:
        AccessKey: "$AWS_ACCESS_KEY"
        RoleARN: "$AWS_ROLE_ARN"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
   PermissionConfigFile: <<MINIO_FILE_PATH>>
fromDate: 2024-08-12
toDate: 2024-08-12
