[Request]
URL = "https://develop.snipeitapp.com/api/v1/hardware"
Method = "GET"
ContentType = "application/json"
Redirect = true
CredentialType = "BearerToken"
TimeOut = 30
Verify = true
MaxWorkers = 5

[Request.Headers]
Accept = "application/json"

[Request.Params]

[Request.Retries.RetryOnCondition]
ConditionField = "<<response.status_code>>"
ConditionValue = "503|504|429|500"
TimeInterval = 2
MaxRetries = 3
RetryBaseDelay = 2
RetryMaxDelay = 60
