userObject:
  app:
    name: Kubernetes 
    appURL: "$INSTANCE_LOGIN_URL"
    appPort: "0"
    appTags:
      appType:
      - kubernetes
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      Jumphost:
        SshPrivateKey: "$INSTANCE_SSH_PRIVATE_KEY"
        UserID: "$INSTANCE_USER_NAME"
userInputs:
  IncludeCriteria: 
  ExcludeCriteria: 
fromDate: 2024-06-26T06:03:00Z
toDate: 2024-06-26T06:03:00Z