userObject:
  app:
    name: Kubernetes
    appPort: "0"
    appURL: "$INSTANCE_LOGIN_URL"
    userDefinedCredentials:
      Jumphost:
        SshPrivateKey: "$INSTANCE_SSH_PRIVATE_KEY"
        UserID: "$INSTANCE_USER_NAME"
userInputs:
  ControlNumber : "" # If you want to see all the control reports then give '*' or leave it empty , If u want control specific the give the control number
  RuleConfig : <<MINIO_FILE_PATH>>
fromDate: 2023-11-24
toDate: 2023-11-24


