userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY" 
        SecretKey: "$AWS_SECRET_KEY"
      AWSRole:
        AccessKey: "$AWS_ACCESS_KEY"
        RoleARN: "$AWS_ROLE_ARN"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  AWSEventsLogFile: <<MINIO_FILE_PATH>>
  AWSUserDetailsLogFile: <<MINIO_FILE_PATH>>
  InactivePermissionsWindow: 
  EventDetails : <<MINIO_FILE_PATH>>
  UserDetails: <<MINIO_FILE_PATH>>
  UserManagerDetails: <<MINIO_FILE_PATH>>
  EventFile: <<MINIO_FILE_PATH>>
fromDate: 2025-04-15T07:21:02Z
toDate: 2025-04-15T07:21:02Z
