authors:
- sangavi.l@continube.com
domain: continube
createdDate: 11/12/2023
name: AWSCredentialReport
displayName: AWS Credential Report
version: '1.0'
description: The report includes a list of IAM users along with information such as their username, ARN (Amazon Resource Name), creation date, password last used date, and whether they have MFA enabled.
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- {}
outputs:
- name: AWSCredentialReport
  description: AWS Credential Report
  type: string
- name: LogFile
  description: AWS Log File
  type: string
- name: CompliancePCT_
  description: Compliance Percentage
  type: int
- name: ComplianceStatus_
  description: Compliance Status
  type: string
