authors:
- tamil.k@continube.com
domain: continube
createdDate: 20/05/2025
name: CreateJiraIssueWithTemplate
displayName: CreateJiraIssueWithTemplate
version: '1.0'
description: CreateJiraIssueWithTemplate
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: JiraIssueTemplate
  description: Jira issue template
  dataType: FILE 
  repeated: false 
  allowedValues: [] 
  defaultValue: <<MINIO_FILE_URL>> 
  showField: true  
  required: true 
- name: JiraInstanceConfigFile
  description: Jira instance configuration file
  dataType: FILE 
  repeated: false 
  allowedValues: [] 
  defaultValue: <<MINIO_FILE_URL>> 
  showField: true  
  required: true 
outputs:
- name: CreatedTicket
  description: Contains created jira ticket id and key
  dataType: FILE
- name: LogFile
  description: Log file of the task
  dataType: FILE
- name: ComplianceStatus_
  description: Compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: Compliance percentage of the task
  dataType: INT
