[JQConfig]
JQExpression = '''[.[] 
| select(.url != null) 
| {
    ResourceUrl: ._links.self.href,
    Branch: .head.ref,
    Title: .title,
    Org: .Org,
    Repo: .Repo,
    Created: .created_at,
    Updated: .updated_at,
    State: .state,
    Number: .number,
    Data: .data,
    Self: ._links.html.href,
    PRReviewers: (.requested_reviewers // [] | map(.login))
}]''' 
OutputMethod = "FIRST" 

