
[Variables]

[Request]

URL = "https://api.github.com/user/repos"

Method = "GET"

ContentType = ""

Redirect = true

CredentialType = "BearerToken"

TimeOut = 30

Verify = true

Retries = 3

RetryOnStatus = [503, 504, 429]

[Request.Headers]
XGitHubApiVersion = "2022-11-28"
Accept = "application/vnd.github+json"

