
[AddColumn]
 System = "github"
 Source = "compliancecow"
 ResourceID = "<<inputfile1.Number>>"
 ResourceName = "<<inputfile1.Title>>"
 ResourceType = "Pull Request"
 ResourceUrl = "<<inputfile1.ResourceUrl>>"  
 ResourceTags = "N/A"
 RepositoryName = "<<inputfile1.Repo>>"
 OrganizationName = "<<inputfile1.Org>>"
 BranchName = "<<inputfile1.Branch>>" 
 PRRequestedDateTime = "<<inputfile1.Created>>"
 PRReviewers = "<<inputfile1.PRReviewers>>"
 PullRequestState = "<<inputfile1.State>>"
 UserAction = ""
 ActionStatus = ""
 ActionResponseURL = ""


[[AddColumn.ByCondition]]
 Condition = "<<inputfile1.CompliantStatus>> == 1" 

[[AddColumn.ByCondition.True]]
 ValidationStatusCode = "CODE_OWNR_PRES_IN_REVR"
 ValidationStatusNotes = "PR includes atleast one code owner as a reviewer."
 ComplianceStatus = "COMPLIANT"
 ComplianceStatusReason = "At least one reviewer in 'Required reviewers'  have a code owner"

[[AddColumn.ByCondition.False]]
 ValidationStatusCode = "CODE_OWNR_NOT_PRES_IN_REVR	"
 ValidationStatusNotes = "PR does not have at least one code owner as requested reviewers.|"
 ComplianceStatus = "NON_COMPLIANT"
 ComplianceStatusReason = "PR should have at least one code owner as required reviewers."

[ReorderColumn]
 "ColumnList" = "System,Source,ResourceID,ResourceName,ResourceType,ResourceUrl,ResourceTags,RepositoryName,OrganizationName,BranchName,PRRequestedDateTime,PRReviewers,PullRequestState,ValidationStatusCode,ValidationStatusNotes,ComplianceStatus,ComplianceStatusReason,UserAction,ActionStatus,ActionResponseURL" # New column order

