userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSRole:
        AccessKey: "$AWS_ROLE_ACCESS_KEY"
        SecretKey: "$AWS_ROLE_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  Region:  []
  EventFile: <<MINIO_FILE_PATH>>
  ResourceFile: <<MINIO_FILE_PATH>>
fromDate: 2025-04-15T07:07:59Z
toDate: 2025-04-15T07:07:59Z
