[Response.Filter]
JQExpression = ".records[]"
OutputMethod = "ALL"

[Response.RuleSet.AppendColumnCondition]
ConditionField = "<<response.status_code>>"
ConditionValue = "200"

[Response.RuleSet.AppendColumn]
IncludeAllInputFields = false

[Response.RuleSet.PaginationCondition]
ConditionField = "<<response.body.count>>"
ConditionValue = "0"

[Response.RuleSet.Pagination]

[Response.RuleSet.AppendColumn.Fields]

[Response.RuleSet.Pagination.Header]

[Response.RuleSet.Pagination.Params]
name = "<<inputfile.EngagementName>>"
page = "<<response.body.page>> + 1"

[Response.RuleSet.Pagination.Data.URLEncoded]

[Response.RuleSet.Pagination.Data.FormData]

[Response.RuleSet.Pagination.Data.Raw]

[Response.RuleSet.Pagination.Data.Binary]
