[Request]
URL = "https://api.github.com/graphql"
Method = "POST"
ContentType = "application/json"
Redirect = true
CredentialType = "JWTBearer"
TimeOut = 30
Verify = true

[Request.Retries.RetryOnCondition]

ConditionField = "<<response.status_code>>"
ConditionValue = "503|504|429|403"
MaxRetries = 3
TimeInterval = "<<response.headers.Retry-After>>"

[Request.Headers]
Cookie = "_octo=GH1.1.854098947.1723007797; logged_in=no"
Accept = "application/vnd.github+json"
Authorization = "Bearer <<validationCURLresponse.token>>"


[Request.Params]


[Request.Data]
    [Request.Data.Raw]
    Value = '{"query":"query ($queryString: String!, $afterCursor: String) {\n    search(query: $queryString, type: ISSUE, first: 50, after: $afterCursor) {\n        pageInfo {\n            endCursor\n            hasNextPage\n        }\n        issueCount\n        nodes {\n            ... on PullRequest {\n                commits(last: 10) {\n                    nodes {\n                        commit {\n                            checkSuites(last: 10) {\n                                nodes {\n                                    checkRuns(last: 50) {\n                                        nodes {\n                                            completedAt\n                                            conclusion\n                                            id\n                                            name\n                                            title\n                                            url\n                                            status\n                                            startedAt\n                                        }\n                                        totalCount\n                                    }\n                                }\n                            }\n                        }\n                    }\n                }\n                headRepository {\n                    nameWithOwner\n                }\n                id\n                title\n                number\n            }\n        }\n    }\n}\n","variables":{"queryString":"repo:<<inputfile.RepositoryName>> type:pr is:merged created:<<fromdate>>..<<todate>>","afterCursor":""}}'
