[JQConfig]
JQExpression = '''
[.[].data.search.nodes[] as $pr | $pr.commits.nodes[].commit.checkSuites.nodes[].checkRuns.nodes[] | {
    "System": "github",
    "Source": "compliancecow",
    "ResourceID": .id,
    "ResourceName": .name,
    "ResourceType": "Check Run",
    "ResourceLocation": "N/A",
    "ResourceTags": [],
    "ResourceURL": .url,
    "RepositoryName": $pr.headRepository.nameWithOwner,
    "PullRequestID": $pr.id,
    "PullRequestTitle": $pr.title,
    "PullRequestNumber": $pr.number,
    "RunStatus": .status,
    "RunConclusion": .conclusion,
    "RunStartedDate": .startedAt,
    "RunCompletedDate": .completedAt
}]
'''
