userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSRole:
        AccessKey: "$AWS_ROLE_ACCESS_KEY"
        SecretKey: "$AWS_ROLE_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  AWSEFSList: <<MINIO_FILE_PATH>>
  KubernetesPVList: <<MINIO_FILE_PATH>>
  KubernetesPVListLogFile: <<MINIO_FILE_PATH>>
  AWSEFSListLogFile: <<MINIO_FILE_PATH>>
fromDate: 2025-04-15T09:04:59Z
toDate: 2025-04-15T09:04:59Z
